name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: osrf/ros:noetic-desktop-full 

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up ROS environment
      run: |
        source /opt/ros/noetic/setup.bash
        echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
        
    - name: Run tests with coverage
      run: |
        source /opt/ros/noetic/setup.bash
        python -m coverage run -m unittest discover
        python -m coverage report
