name: Python Tests with ROS

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros-distro: ["noetic"]  # Change to your ROS2 distro (foxy, galactic, etc.)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up ROS
      uses: ros-tooling/setup-ros@v1
      with:
        required-ros-distributions: ${{ matrix.ros-distro }}
    
    - name: Source ROS environment
      run: |
        source /opt/ros/${{ matrix.ros-distro }}/setup.bash
        echo "source /opt/ros/${{ matrix.ros-distro }}/setup.bash" >> ~/.bashrc
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests with coverage
      run: |
        source /opt/ros/${{ matrix.ros-distro }}/setup.bash
        python -m coverage run -m unittest discover
        python -m coverage report
