name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Aún necesitamos un runner para Docker, pero no necesita ser Ubuntu 20.04

    container:
      image: osrf/ros:noetic-desktop-full  # Usamos la imagen oficial con ROS Noetic

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install curl and pip
      run: |
        sudo apt update
        sudo apt install -y curl
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py  # Esto instalará pip para Python 3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up ROS environment
      run: |
        bash -c "source /opt/ros/noetic/setup.bash"  # Usamos bash explícitamente para ejecutar el script de ROS
        echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc  # Hace persistente la configuración
        
    - name: Run tests with coverage
      run: |
        bash -c "source /opt/ros/noetic/setup.bash"  # Usamos bash explícitamente para ejecutar el script de ROS
        python3 -m coverage run -m unittest discover
        python3 -m coverage report
